/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";
import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as AboutRouteRouteImport } from "./routes/about/route";
import { Route as authRouteRouteImport } from "./routes/(auth)/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AboutIndexRouteImport } from "./routes/about/index";
import { Route as AppAppRouteImport } from "./routes/app/_app";
import { Route as authSignupRouteImport } from "./routes/(auth)/signup";
import { Route as authLoginRouteImport } from "./routes/(auth)/login";
import { Route as AppAppIndexRouteImport } from "./routes/app/_app/index";
import { Route as AppAppSettingsRouteImport } from "./routes/app/_app/settings";
import { Route as AppAppRecordsRouteImport } from "./routes/app/_app/records";
import { Route as AppAppMembersRouteImport } from "./routes/app/_app/members";
import { Route as AppAppChatsRouteImport } from "./routes/app/_app/chats";
import { Route as AppAppChatChatIdRouteImport } from "./routes/app/_app/chat.$chatId";
import { ServerRoute as ApiHelloServerRouteImport } from "./routes/api/hello";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";
import { ServerRoute as ApiAiMessagesServerRouteImport } from "./routes/api/ai.messages";
import { ServerRoute as ApiAiChatServerRouteImport } from "./routes/api/ai.chat";

const AppRouteImport = createFileRoute("/app")();
const rootServerRouteImport = createServerRootRoute();

const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AboutRouteRoute,
} as any);
const AppAppRoute = AppAppRouteImport.update({
  id: "/_app",
  getParentRoute: () => AppRoute,
} as any);
const authSignupRoute = authSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => authRouteRoute,
} as any);
const authLoginRoute = authLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => authRouteRoute,
} as any);
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppSettingsRoute = AppAppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppRecordsRoute = AppAppRecordsRouteImport.update({
  id: "/records",
  path: "/records",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppMembersRoute = AppAppMembersRouteImport.update({
  id: "/members",
  path: "/members",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppChatsRoute = AppAppChatsRouteImport.update({
  id: "/chats",
  path: "/chats",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppChatChatIdRoute = AppAppChatChatIdRouteImport.update({
  id: "/chat/$chatId",
  path: "/chat/$chatId",
  getParentRoute: () => AppAppRoute,
} as any);
const ApiHelloServerRoute = ApiHelloServerRouteImport.update({
  id: "/api/hello",
  path: "/api/hello",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiAiMessagesServerRoute = ApiAiMessagesServerRouteImport.update({
  id: "/api/ai/messages",
  path: "/api/ai/messages",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiAiChatServerRoute = ApiAiChatServerRouteImport.update({
  id: "/api/ai/chat",
  path: "/api/ai/chat",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof authRouteRouteWithChildren;
  "/about": typeof AboutRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/app": typeof AppAppRouteWithChildren;
  "/about/": typeof AboutIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/app/chats": typeof AppAppChatsRoute;
  "/app/members": typeof AppAppMembersRoute;
  "/app/records": typeof AppAppRecordsRoute;
  "/app/settings": typeof AppAppSettingsRoute;
  "/app/": typeof AppAppIndexRoute;
  "/app/chat/$chatId": typeof AppAppChatChatIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof authRouteRouteWithChildren;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/app": typeof AppAppIndexRoute;
  "/about": typeof AboutIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/app/chats": typeof AppAppChatsRoute;
  "/app/members": typeof AppAppMembersRoute;
  "/app/records": typeof AppAppRecordsRoute;
  "/app/settings": typeof AppAppSettingsRoute;
  "/app/chat/$chatId": typeof AppAppChatChatIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/(auth)": typeof authRouteRouteWithChildren;
  "/about": typeof AboutRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/(auth)/login": typeof authLoginRoute;
  "/(auth)/signup": typeof authSignupRoute;
  "/app": typeof AppRouteWithChildren;
  "/app/_app": typeof AppAppRouteWithChildren;
  "/about/": typeof AboutIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/app/_app/chats": typeof AppAppChatsRoute;
  "/app/_app/members": typeof AppAppMembersRoute;
  "/app/_app/records": typeof AppAppRecordsRoute;
  "/app/_app/settings": typeof AppAppSettingsRoute;
  "/app/_app/": typeof AppAppIndexRoute;
  "/app/_app/chat/$chatId": typeof AppAppChatChatIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/dashboard"
    | "/login"
    | "/signup"
    | "/app"
    | "/about/"
    | "/dashboard/"
    | "/app/chats"
    | "/app/members"
    | "/app/records"
    | "/app/settings"
    | "/app/"
    | "/app/chat/$chatId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/signup"
    | "/app"
    | "/about"
    | "/dashboard"
    | "/app/chats"
    | "/app/members"
    | "/app/records"
    | "/app/settings"
    | "/app/chat/$chatId";
  id:
    | "__root__"
    | "/"
    | "/(auth)"
    | "/about"
    | "/dashboard"
    | "/(auth)/login"
    | "/(auth)/signup"
    | "/app"
    | "/app/_app"
    | "/about/"
    | "/dashboard/"
    | "/app/_app/chats"
    | "/app/_app/members"
    | "/app/_app/records"
    | "/app/_app/settings"
    | "/app/_app/"
    | "/app/_app/chat/$chatId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  authRouteRoute: typeof authRouteRouteWithChildren;
  AboutRouteRoute: typeof AboutRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  AppRoute: typeof AppRouteWithChildren;
}
export interface FileServerRoutesByFullPath {
  "/api/hello": typeof ApiHelloServerRoute;
  "/api/ai/chat": typeof ApiAiChatServerRoute;
  "/api/ai/messages": typeof ApiAiMessagesServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/hello": typeof ApiHelloServerRoute;
  "/api/ai/chat": typeof ApiAiChatServerRoute;
  "/api/ai/messages": typeof ApiAiMessagesServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/hello": typeof ApiHelloServerRoute;
  "/api/ai/chat": typeof ApiAiChatServerRoute;
  "/api/ai/messages": typeof ApiAiMessagesServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths: "/api/hello" | "/api/ai/chat" | "/api/ai/messages" | "/api/auth/$";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to: "/api/hello" | "/api/ai/chat" | "/api/ai/messages" | "/api/auth/$";
  id:
    | "__root__"
    | "/api/hello"
    | "/api/ai/chat"
    | "/api/ai/messages"
    | "/api/auth/$";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiHelloServerRoute: typeof ApiHelloServerRoute;
  ApiAiChatServerRoute: typeof ApiAiChatServerRoute;
  ApiAiMessagesServerRoute: typeof ApiAiMessagesServerRoute;
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)": {
      id: "/(auth)";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof authRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/about/": {
      id: "/about/";
      path: "/";
      fullPath: "/about/";
      preLoaderRoute: typeof AboutIndexRouteImport;
      parentRoute: typeof AboutRouteRoute;
    };
    "/app/_app": {
      id: "/app/_app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppAppRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/(auth)/signup": {
      id: "/(auth)/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof authSignupRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(auth)/login": {
      id: "/(auth)/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof authLoginRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/app/_app/": {
      id: "/app/_app/";
      path: "/";
      fullPath: "/app/";
      preLoaderRoute: typeof AppAppIndexRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/settings": {
      id: "/app/_app/settings";
      path: "/settings";
      fullPath: "/app/settings";
      preLoaderRoute: typeof AppAppSettingsRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/records": {
      id: "/app/_app/records";
      path: "/records";
      fullPath: "/app/records";
      preLoaderRoute: typeof AppAppRecordsRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/members": {
      id: "/app/_app/members";
      path: "/members";
      fullPath: "/app/members";
      preLoaderRoute: typeof AppAppMembersRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/chats": {
      id: "/app/_app/chats";
      path: "/chats";
      fullPath: "/app/chats";
      preLoaderRoute: typeof AppAppChatsRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/chat/$chatId": {
      id: "/app/_app/chat/$chatId";
      path: "/chat/$chatId";
      fullPath: "/app/chat/$chatId";
      preLoaderRoute: typeof AppAppChatChatIdRouteImport;
      parentRoute: typeof AppAppRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/hello": {
      id: "/api/hello";
      path: "/api/hello";
      fullPath: "/api/hello";
      preLoaderRoute: typeof ApiHelloServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/ai/messages": {
      id: "/api/ai/messages";
      path: "/api/ai/messages";
      fullPath: "/api/ai/messages";
      preLoaderRoute: typeof ApiAiMessagesServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/ai/chat": {
      id: "/api/ai/chat";
      path: "/api/ai/chat";
      fullPath: "/api/ai/chat";
      preLoaderRoute: typeof ApiAiChatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute;
  authSignupRoute: typeof authSignupRoute;
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
};

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
);

interface AboutRouteRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute;
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
};

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface AppAppRouteChildren {
  AppAppChatsRoute: typeof AppAppChatsRoute;
  AppAppMembersRoute: typeof AppAppMembersRoute;
  AppAppRecordsRoute: typeof AppAppRecordsRoute;
  AppAppSettingsRoute: typeof AppAppSettingsRoute;
  AppAppIndexRoute: typeof AppAppIndexRoute;
  AppAppChatChatIdRoute: typeof AppAppChatChatIdRoute;
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppChatsRoute: AppAppChatsRoute,
  AppAppMembersRoute: AppAppMembersRoute,
  AppAppRecordsRoute: AppAppRecordsRoute,
  AppAppSettingsRoute: AppAppSettingsRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppChatChatIdRoute: AppAppChatChatIdRoute,
};

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren);

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRouteWithChildren;
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRouteWithChildren,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AboutRouteRoute: AboutRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiHelloServerRoute: ApiHelloServerRoute,
  ApiAiChatServerRoute: ApiAiChatServerRoute,
  ApiAiMessagesServerRoute: ApiAiMessagesServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
