/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";
import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as AboutRouteRouteImport } from "./routes/about/route";
import { Route as authRouteRouteImport } from "./routes/(auth)/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AboutIndexRouteImport } from "./routes/about/index";
import { Route as AppAppRouteImport } from "./routes/app/_app";
import { Route as authSignupRouteImport } from "./routes/(auth)/signup";
import { Route as authLoginRouteImport } from "./routes/(auth)/login";
import { Route as AppAppIndexRouteImport } from "./routes/app/_app/index";
import { Route as AppAppSleepRouteImport } from "./routes/app/_app/sleep";
import { Route as AppAppSettingsRouteImport } from "./routes/app/_app/settings";
import { Route as AppAppRecordsRouteImport } from "./routes/app/_app/records";
import { Route as AppAppMembersRouteImport } from "./routes/app/_app/members";
import { Route as AppAppMedicinesRouteImport } from "./routes/app/_app/medicines";
import { Route as AppAppHomeRouteImport } from "./routes/app/_app/home";
import { Route as AppAppExerciseRouteImport } from "./routes/app/_app/exercise";
import { Route as AppAppDietRouteImport } from "./routes/app/_app/diet";
import { Route as AppAppChatsRouteImport } from "./routes/app/_app/chats";
import { Route as AppAppCalendarRouteImport } from "./routes/app/_app/calendar";
import { Route as ApiAiUploadRouteImport } from "./routes/api/ai.upload";
import { Route as ApiAiQueryRouteImport } from "./routes/api/ai.query";
import { Route as AppAppChatChatIdRouteImport } from "./routes/app/_app/chat.$chatId";
import { ServerRoute as ApiUploadServerRouteImport } from "./routes/api/upload";
import { ServerRoute as ApiMediaServerRouteImport } from "./routes/api/media";
import { ServerRoute as ApiHelloServerRouteImport } from "./routes/api/hello";
import { ServerRoute as ApiUploadFileServerRouteImport } from "./routes/api/upload.file";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";
import { ServerRoute as ApiAiChatServerRouteImport } from "./routes/api/ai.chat";

const AppRouteImport = createFileRoute("/app")();
const rootServerRouteImport = createServerRootRoute();

const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AboutRouteRoute,
} as any);
const AppAppRoute = AppAppRouteImport.update({
  id: "/_app",
  getParentRoute: () => AppRoute,
} as any);
const authSignupRoute = authSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => authRouteRoute,
} as any);
const authLoginRoute = authLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => authRouteRoute,
} as any);
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppSleepRoute = AppAppSleepRouteImport.update({
  id: "/sleep",
  path: "/sleep",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppSettingsRoute = AppAppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppRecordsRoute = AppAppRecordsRouteImport.update({
  id: "/records",
  path: "/records",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppMembersRoute = AppAppMembersRouteImport.update({
  id: "/members",
  path: "/members",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppMedicinesRoute = AppAppMedicinesRouteImport.update({
  id: "/medicines",
  path: "/medicines",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppHomeRoute = AppAppHomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppExerciseRoute = AppAppExerciseRouteImport.update({
  id: "/exercise",
  path: "/exercise",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppDietRoute = AppAppDietRouteImport.update({
  id: "/diet",
  path: "/diet",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppChatsRoute = AppAppChatsRouteImport.update({
  id: "/chats",
  path: "/chats",
  getParentRoute: () => AppAppRoute,
} as any);
const AppAppCalendarRoute = AppAppCalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => AppAppRoute,
} as any);
const ApiAiUploadRoute = ApiAiUploadRouteImport.update({
  id: "/api/ai/upload",
  path: "/api/ai/upload",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAiQueryRoute = ApiAiQueryRouteImport.update({
  id: "/api/ai/query",
  path: "/api/ai/query",
  getParentRoute: () => rootRouteImport,
} as any);
const AppAppChatChatIdRoute = AppAppChatChatIdRouteImport.update({
  id: "/chat/$chatId",
  path: "/chat/$chatId",
  getParentRoute: () => AppAppRoute,
} as any);
const ApiUploadServerRoute = ApiUploadServerRouteImport.update({
  id: "/api/upload",
  path: "/api/upload",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiMediaServerRoute = ApiMediaServerRouteImport.update({
  id: "/api/media",
  path: "/api/media",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiHelloServerRoute = ApiHelloServerRouteImport.update({
  id: "/api/hello",
  path: "/api/hello",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiUploadFileServerRoute = ApiUploadFileServerRouteImport.update({
  id: "/file",
  path: "/file",
  getParentRoute: () => ApiUploadServerRoute,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiAiChatServerRoute = ApiAiChatServerRouteImport.update({
  id: "/api/ai/chat",
  path: "/api/ai/chat",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof authRouteRouteWithChildren;
  "/about": typeof AboutRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/app": typeof AppAppRouteWithChildren;
  "/about/": typeof AboutIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/api/ai/query": typeof ApiAiQueryRoute;
  "/api/ai/upload": typeof ApiAiUploadRoute;
  "/app/calendar": typeof AppAppCalendarRoute;
  "/app/chats": typeof AppAppChatsRoute;
  "/app/diet": typeof AppAppDietRoute;
  "/app/exercise": typeof AppAppExerciseRoute;
  "/app/home": typeof AppAppHomeRoute;
  "/app/medicines": typeof AppAppMedicinesRoute;
  "/app/members": typeof AppAppMembersRoute;
  "/app/records": typeof AppAppRecordsRoute;
  "/app/settings": typeof AppAppSettingsRoute;
  "/app/sleep": typeof AppAppSleepRoute;
  "/app/": typeof AppAppIndexRoute;
  "/app/chat/$chatId": typeof AppAppChatChatIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof authRouteRouteWithChildren;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/app": typeof AppAppIndexRoute;
  "/about": typeof AboutIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/api/ai/query": typeof ApiAiQueryRoute;
  "/api/ai/upload": typeof ApiAiUploadRoute;
  "/app/calendar": typeof AppAppCalendarRoute;
  "/app/chats": typeof AppAppChatsRoute;
  "/app/diet": typeof AppAppDietRoute;
  "/app/exercise": typeof AppAppExerciseRoute;
  "/app/home": typeof AppAppHomeRoute;
  "/app/medicines": typeof AppAppMedicinesRoute;
  "/app/members": typeof AppAppMembersRoute;
  "/app/records": typeof AppAppRecordsRoute;
  "/app/settings": typeof AppAppSettingsRoute;
  "/app/sleep": typeof AppAppSleepRoute;
  "/app/chat/$chatId": typeof AppAppChatChatIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/(auth)": typeof authRouteRouteWithChildren;
  "/about": typeof AboutRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/(auth)/login": typeof authLoginRoute;
  "/(auth)/signup": typeof authSignupRoute;
  "/app": typeof AppRouteWithChildren;
  "/app/_app": typeof AppAppRouteWithChildren;
  "/about/": typeof AboutIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/api/ai/query": typeof ApiAiQueryRoute;
  "/api/ai/upload": typeof ApiAiUploadRoute;
  "/app/_app/calendar": typeof AppAppCalendarRoute;
  "/app/_app/chats": typeof AppAppChatsRoute;
  "/app/_app/diet": typeof AppAppDietRoute;
  "/app/_app/exercise": typeof AppAppExerciseRoute;
  "/app/_app/home": typeof AppAppHomeRoute;
  "/app/_app/medicines": typeof AppAppMedicinesRoute;
  "/app/_app/members": typeof AppAppMembersRoute;
  "/app/_app/records": typeof AppAppRecordsRoute;
  "/app/_app/settings": typeof AppAppSettingsRoute;
  "/app/_app/sleep": typeof AppAppSleepRoute;
  "/app/_app/": typeof AppAppIndexRoute;
  "/app/_app/chat/$chatId": typeof AppAppChatChatIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/dashboard"
    | "/login"
    | "/signup"
    | "/app"
    | "/about/"
    | "/dashboard/"
    | "/api/ai/query"
    | "/api/ai/upload"
    | "/app/calendar"
    | "/app/chats"
    | "/app/diet"
    | "/app/exercise"
    | "/app/home"
    | "/app/medicines"
    | "/app/members"
    | "/app/records"
    | "/app/settings"
    | "/app/sleep"
    | "/app/"
    | "/app/chat/$chatId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/signup"
    | "/app"
    | "/about"
    | "/dashboard"
    | "/api/ai/query"
    | "/api/ai/upload"
    | "/app/calendar"
    | "/app/chats"
    | "/app/diet"
    | "/app/exercise"
    | "/app/home"
    | "/app/medicines"
    | "/app/members"
    | "/app/records"
    | "/app/settings"
    | "/app/sleep"
    | "/app/chat/$chatId";
  id:
    | "__root__"
    | "/"
    | "/(auth)"
    | "/about"
    | "/dashboard"
    | "/(auth)/login"
    | "/(auth)/signup"
    | "/app"
    | "/app/_app"
    | "/about/"
    | "/dashboard/"
    | "/api/ai/query"
    | "/api/ai/upload"
    | "/app/_app/calendar"
    | "/app/_app/chats"
    | "/app/_app/diet"
    | "/app/_app/exercise"
    | "/app/_app/home"
    | "/app/_app/medicines"
    | "/app/_app/members"
    | "/app/_app/records"
    | "/app/_app/settings"
    | "/app/_app/sleep"
    | "/app/_app/"
    | "/app/_app/chat/$chatId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  authRouteRoute: typeof authRouteRouteWithChildren;
  AboutRouteRoute: typeof AboutRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  AppRoute: typeof AppRouteWithChildren;
  ApiAiQueryRoute: typeof ApiAiQueryRoute;
  ApiAiUploadRoute: typeof ApiAiUploadRoute;
}
export interface FileServerRoutesByFullPath {
  "/api/hello": typeof ApiHelloServerRoute;
  "/api/media": typeof ApiMediaServerRoute;
  "/api/upload": typeof ApiUploadServerRouteWithChildren;
  "/api/ai/chat": typeof ApiAiChatServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/upload/file": typeof ApiUploadFileServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/hello": typeof ApiHelloServerRoute;
  "/api/media": typeof ApiMediaServerRoute;
  "/api/upload": typeof ApiUploadServerRouteWithChildren;
  "/api/ai/chat": typeof ApiAiChatServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/upload/file": typeof ApiUploadFileServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/hello": typeof ApiHelloServerRoute;
  "/api/media": typeof ApiMediaServerRoute;
  "/api/upload": typeof ApiUploadServerRouteWithChildren;
  "/api/ai/chat": typeof ApiAiChatServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/upload/file": typeof ApiUploadFileServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths:
    | "/api/hello"
    | "/api/media"
    | "/api/upload"
    | "/api/ai/chat"
    | "/api/auth/$"
    | "/api/upload/file";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to:
    | "/api/hello"
    | "/api/media"
    | "/api/upload"
    | "/api/ai/chat"
    | "/api/auth/$"
    | "/api/upload/file";
  id:
    | "__root__"
    | "/api/hello"
    | "/api/media"
    | "/api/upload"
    | "/api/ai/chat"
    | "/api/auth/$"
    | "/api/upload/file";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiHelloServerRoute: typeof ApiHelloServerRoute;
  ApiMediaServerRoute: typeof ApiMediaServerRoute;
  ApiUploadServerRoute: typeof ApiUploadServerRouteWithChildren;
  ApiAiChatServerRoute: typeof ApiAiChatServerRoute;
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)": {
      id: "/(auth)";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof authRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/about/": {
      id: "/about/";
      path: "/";
      fullPath: "/about/";
      preLoaderRoute: typeof AboutIndexRouteImport;
      parentRoute: typeof AboutRouteRoute;
    };
    "/app/_app": {
      id: "/app/_app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppAppRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/(auth)/signup": {
      id: "/(auth)/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof authSignupRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(auth)/login": {
      id: "/(auth)/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof authLoginRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/app/_app/": {
      id: "/app/_app/";
      path: "/";
      fullPath: "/app/";
      preLoaderRoute: typeof AppAppIndexRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/sleep": {
      id: "/app/_app/sleep";
      path: "/sleep";
      fullPath: "/app/sleep";
      preLoaderRoute: typeof AppAppSleepRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/settings": {
      id: "/app/_app/settings";
      path: "/settings";
      fullPath: "/app/settings";
      preLoaderRoute: typeof AppAppSettingsRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/records": {
      id: "/app/_app/records";
      path: "/records";
      fullPath: "/app/records";
      preLoaderRoute: typeof AppAppRecordsRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/members": {
      id: "/app/_app/members";
      path: "/members";
      fullPath: "/app/members";
      preLoaderRoute: typeof AppAppMembersRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/medicines": {
      id: "/app/_app/medicines";
      path: "/medicines";
      fullPath: "/app/medicines";
      preLoaderRoute: typeof AppAppMedicinesRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/home": {
      id: "/app/_app/home";
      path: "/home";
      fullPath: "/app/home";
      preLoaderRoute: typeof AppAppHomeRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/exercise": {
      id: "/app/_app/exercise";
      path: "/exercise";
      fullPath: "/app/exercise";
      preLoaderRoute: typeof AppAppExerciseRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/diet": {
      id: "/app/_app/diet";
      path: "/diet";
      fullPath: "/app/diet";
      preLoaderRoute: typeof AppAppDietRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/chats": {
      id: "/app/_app/chats";
      path: "/chats";
      fullPath: "/app/chats";
      preLoaderRoute: typeof AppAppChatsRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/app/_app/calendar": {
      id: "/app/_app/calendar";
      path: "/calendar";
      fullPath: "/app/calendar";
      preLoaderRoute: typeof AppAppCalendarRouteImport;
      parentRoute: typeof AppAppRoute;
    };
    "/api/ai/upload": {
      id: "/api/ai/upload";
      path: "/api/ai/upload";
      fullPath: "/api/ai/upload";
      preLoaderRoute: typeof ApiAiUploadRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/ai/query": {
      id: "/api/ai/query";
      path: "/api/ai/query";
      fullPath: "/api/ai/query";
      preLoaderRoute: typeof ApiAiQueryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/_app/chat/$chatId": {
      id: "/app/_app/chat/$chatId";
      path: "/chat/$chatId";
      fullPath: "/app/chat/$chatId";
      preLoaderRoute: typeof AppAppChatChatIdRouteImport;
      parentRoute: typeof AppAppRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/upload": {
      id: "/api/upload";
      path: "/api/upload";
      fullPath: "/api/upload";
      preLoaderRoute: typeof ApiUploadServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/media": {
      id: "/api/media";
      path: "/api/media";
      fullPath: "/api/media";
      preLoaderRoute: typeof ApiMediaServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/hello": {
      id: "/api/hello";
      path: "/api/hello";
      fullPath: "/api/hello";
      preLoaderRoute: typeof ApiHelloServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/upload/file": {
      id: "/api/upload/file";
      path: "/file";
      fullPath: "/api/upload/file";
      preLoaderRoute: typeof ApiUploadFileServerRouteImport;
      parentRoute: typeof ApiUploadServerRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/ai/chat": {
      id: "/api/ai/chat";
      path: "/api/ai/chat";
      fullPath: "/api/ai/chat";
      preLoaderRoute: typeof ApiAiChatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute;
  authSignupRoute: typeof authSignupRoute;
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
};

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
);

interface AboutRouteRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute;
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
};

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface AppAppRouteChildren {
  AppAppCalendarRoute: typeof AppAppCalendarRoute;
  AppAppChatsRoute: typeof AppAppChatsRoute;
  AppAppDietRoute: typeof AppAppDietRoute;
  AppAppExerciseRoute: typeof AppAppExerciseRoute;
  AppAppHomeRoute: typeof AppAppHomeRoute;
  AppAppMedicinesRoute: typeof AppAppMedicinesRoute;
  AppAppMembersRoute: typeof AppAppMembersRoute;
  AppAppRecordsRoute: typeof AppAppRecordsRoute;
  AppAppSettingsRoute: typeof AppAppSettingsRoute;
  AppAppSleepRoute: typeof AppAppSleepRoute;
  AppAppIndexRoute: typeof AppAppIndexRoute;
  AppAppChatChatIdRoute: typeof AppAppChatChatIdRoute;
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppCalendarRoute: AppAppCalendarRoute,
  AppAppChatsRoute: AppAppChatsRoute,
  AppAppDietRoute: AppAppDietRoute,
  AppAppExerciseRoute: AppAppExerciseRoute,
  AppAppHomeRoute: AppAppHomeRoute,
  AppAppMedicinesRoute: AppAppMedicinesRoute,
  AppAppMembersRoute: AppAppMembersRoute,
  AppAppRecordsRoute: AppAppRecordsRoute,
  AppAppSettingsRoute: AppAppSettingsRoute,
  AppAppSleepRoute: AppAppSleepRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppChatChatIdRoute: AppAppChatChatIdRoute,
};

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren);

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRouteWithChildren;
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRouteWithChildren,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

interface ApiUploadServerRouteChildren {
  ApiUploadFileServerRoute: typeof ApiUploadFileServerRoute;
}

const ApiUploadServerRouteChildren: ApiUploadServerRouteChildren = {
  ApiUploadFileServerRoute: ApiUploadFileServerRoute,
};

const ApiUploadServerRouteWithChildren = ApiUploadServerRoute._addFileChildren(
  ApiUploadServerRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AboutRouteRoute: AboutRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ApiAiQueryRoute: ApiAiQueryRoute,
  ApiAiUploadRoute: ApiAiUploadRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiHelloServerRoute: ApiHelloServerRoute,
  ApiMediaServerRoute: ApiMediaServerRoute,
  ApiUploadServerRoute: ApiUploadServerRouteWithChildren,
  ApiAiChatServerRoute: ApiAiChatServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
